

services:
- type: web
  name: allopromo_Db
  runtime: image    
  plan: free
  region: oregon
  image:
    url: mcr.microsoft.com/mssql/server:2017-latest
  envVars:
    - key: ACCEPT_EULA
      value: "Y"
    - key : MSSQL_SA_PASSWORD
      value: "myStrong@Passw0rd"