

services:
  - type: web
    name: allopromoApi
    runtime: docker
    repo: https://github.com/ufufuu/allopromos
    plan: free
    region: oregon
    autoDeploy: false
    dockerContext: .
    dockerfilePath: src/allopromo.Api/Dockerfile
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
        - key: SQLHOST
          fromDatabase:
            name: allopromoDB
            property:connectionString
        - key : SQLPORT
          fromDatabase:
            name: allopromoDB
            property: PORT
        - key: PGUSER
          fromDatabase:
            name: lightdash-database
            property: user
        - key: PGPASSWORD
          fromDatabase:
            name: lightdash-database
            property: password
        
  - type: web
    name: allopromo_DBServer
    runtime: docker
    repo: https://github.com/ufufuu/allopromos
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: src/allopromo.Infrastructure/Dockerfile
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: MSSQL_SA_PASSWORD
        value: "YourStrong@Passw0rd"
    disk:
      - name: data
      - mountPath: /var/opt/mssql
      - sizeGB: 10