services:
  - type: pserv
    name: mssql
    
    # env: image
    # image:
    #   url: mcr.microsoft.com/mssql/server:2017-latest

    env: docker
    repo: https://github.com/jonahgeorge/render-examples-mssql.git
    branch: main
    
    plan: standard
    autoDeploy: false
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: MSSQL_SA_PASSWORD
        value: "YourStrong@Passw0rd"
    disk:
      name: data
      mountPath: /var/opt/mssql
      sizeGB: 10