
# Exported from Render on 2025-04-12T17:52:53Z 

# COPY --from=builder /initialized-db /var/lib/mysql
services:
    - type: web
      runtime: docker
      name: allopromoApi
      repo: https://github.com/ufufuu/allopromos
      plan: free
      region: oregon
      dockerContext: .
      dockerfilePath: src/allopromo.Api/Dockerfile
    version: "1"
    - type: web
      runtime: docker
      name: allopromoDB
      repo: mcr.microsoft.com/mssql/server:2019-latest
      plan: free
      region: oregon
      dockerContext: .
      dockerfilePath: src/allopromo.Infrastructure/Dockerfile
    version: "1"