

services:
- type: web
  name: allopromo_Db
  runtime: image    
  plan: free
  region: oregon
  
  
- type: web
  name: allopromo_Api
  runtime: docker
  repo: https://github.com/ufufuu/allopromos
  plan: free
  region: oregon
  autoDeploy: false
  numInstances: 1
  healthCheckPath: /healthz
envVarGroups:
