
services:
- type: pserv
  name: sqlserver
  plan: free
  env: docker
  autoDeploy: false
  envVars:
  - fromGroup: mssql
  
- type: web
  name: allopromoApi
  runtime: docker
  repo: https://github.com/ufufuu/allopromos
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: src/allopromo.Api/Dockerfile
  numInstances: 1
  healthCheckPath: /healthz
  
  
  
# https://vijayasimhabr.medium.com/running-microsoft-sql-database-server-with-docker-5a879ef06adb