

services:
- type: web
    name: allopromoDB
    runtime: image
    plan: free
    region: oregon
    envVars:
    - fromGroup: allopromo_mssql_server
- type: web
    name: allopromoApi
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: false
    numInstances: 1
    healthCheckPath: /healthz
    
envVarGroups:
    - name : allopromo_mssql_server
     envVars:
     - key: ACCEPT_EULA
     value: "Y"
     - key: MSSQL_SA_PASSWORD
     value: "YourStrong@Passw0rd"