
services:
- type: pserv
  name: sqlserver
  plan: free
  env: docker
  autoDeploy: false
 
  envVars:
  - fromGroup: mysql
  

- type: web
  name: allopromoApi
  runtime: docker
  repo: https://github.com/ufufuu/allopromos
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: src/allopromo.Api/Dockerfile
  numInstances: 1
  healthCheckPath: /healthz