

services:
- type: web
  name: allopromo_Db
  runtime: image    
  plan: free
  region: oregon
  image:
    url: mcr.microsoft.com/mssql/server:2019-latest
  
- type: web
  name: allopromo_Api
  runtime: docker
  repo: https://github.com/ufufuu/allopromos
  plan: free
  region: oregon
  autoDeploy: false
  numInstances: 1
  healthCheckPath: /healthz
envVarGroups:
